DROP TABLE REFRIGERATOR;

CREATE TABLE REFRIGERATOR(
	REFRIGERATOR_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(20) NOT NULL,
	REFRIGERATOR_MATERIAL VARCHAR2(4000) NOT NULL,
	CONSTRAINT REF_FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

