DROP TABLE RECIPE;
DROP TABLE RECIPE CASCADE CONSTRAINTS;

CREATE TABLE RECIPE(
RECIPE_NO NUMBER PRIMARY KEY,
RECIPE_MAIN_PHOTO VARCHAR2(4000) NOT NULL,
MEMBER_ID VARCHAR2(50) NOT NULL,
RECIPE_TITLE VARCHAR2(100) NOT NULL,
RECIPE_DETAIL VARCHAR2(4000) NOT NULL,
RECIPE_REGDATE DATE DEFAULT(SYSDATE) NOT NULL,
RECIPE_READCOUNT NUMBER DEFAULT(0) NOT NULL,
RECIPE_MATERIAL_ONE VARCHAR2(40) NOT NULL,
RECIPE_THEME NUMBER NOT NULL,
RECIPE_KIND NUMBER NOT NULL,
RECIPE_MATERIAL VARCHAR(1000) NOT NULL,
RECIPE_LIKECOUNT NUMBER DEFAULT(0) NOT NULL,
CONSTRAINT RECIPE_FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
ON DELETE CASCADE,
CONSTRAINT RECIPE_FK_RECIPE_THEME FOREIGN KEY(RECIPE_THEME) REFERENCES CATEGORY(CATEGORY_NO)
ON DELETE CASCADE,
CONSTRAINT RECIPE_FK_RECIPE_KIND FOREIGN KEY(RECIPE_KIND) REFERENCES CATEGORY(CATEGORY_NO)
ON DELETE CASCADE
);



