DROP TABLE BROADCAST_RESERVATION;
DROP TABLE BROADCAST_RESERVATION CASCADE CONSTRAINTS;

CREATE TABLE BROADCAST_RESERVATION(
	RESERVATION_NO NUMBER PRIMARY KEY,
	RESERVATION_TIME DATE DEFAULT(SYSDATE) NOT NULL,
	RESERVATION_CONFIRM VARCHAR2(10) DEFAULT('N') NOT NULL,
	MEMBER_ID VARCHAR2(50) NOT NULL,
	CONSTRAINT RESERVATION_FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) 
	ON DELETE CASCADE,
	CONSTRAINT RESERVATION_CHK_CONF CHECK(RESERVATION_CONFIRM IN ('Y', 'N'))

);
 